### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by skywarspro15** [cherries-to/Cherry-Tree-TV#5]
Cherry Tree currently relies on the Internet to connect with authentication servers. 

When the servers are down, however, the ENTIRE system is inaccessible. This ruins the point of a "local" media oriented system if it requires an Internet connection to run. It's just a worse Xbox One at this point. 🤷

![IMG20240805134255.jpg](https://github.com/user-attachments/assets/9f9646ea-8396-464e-b023-6d64a03c1bed)

**Comment by datkat21** [comment]
Cherry Tree TV is based on the old Cherry Tree Console which is why it depends on the websocket connection for live updates (friend list, etc). The connection failing and causing a softlock seems to be a bug as it could absolutely continue on normally without a connection. (e.g. when you hit Skip from the initial OOBE menu)
